---
name: Hook-Output-File
version: 0.06_01
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
abstract: Redirect STDOUT/STDERR to a file
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  File::Temp: 0
  IO::Capture: 0
  Test::More: 0
requires:
  Carp: 0
  File::Spec: 0
  Tie::Handle: 0
  perl: 5.008
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
configure_requires:
  Module::Build: 0.340201
provides:
  Hook::Output::File:
    file: lib/Hook/Output/File.pm
    version: 0.06_01
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
